### ISSUE TITLE
Audio.musicPlay will not continue playing music, when focus of the game window is received.

### ISSUE THREAD

**Issue by KevinW1998** [WohlSoft/LunaLua#13]
If Audio.musicPlay used and the focus is lost of the SMBX window then the music stopps. However when you set back the focus on the SMBX window, then the music won't continue.

**Comment by Wohlstand** [comment]
To have that working right, you should
- Seize music stream from that section(s) where you trying to play that music
- Section should have configured ANY default except "none" or "custom" music. This is REQUIRED, to tell SMBX that music is playing in that section. BUT, because music stream seized, SMBX Engine can't replace music in stream, therefore you can freely play any music via Lua code.
  If section has "none" music, it doing nothing when you trying to toggle your SMBX window again, because it think that no music to resume.
