### ISSUE TITLE
LunaLoader (in PGE Editor) starts SMBX as vanilla with no hack.

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/LunaLua#16]
After small update in the LunaLUA side, SMBX no more want be started with LunaLUA. Older version of LunaLUA in SMBX 2.0 repo works fine with same latest state of PGE Editor.

**Comment by Bluenaxela** [comment]
I just tested the latest appveyor build of LunaLua just fine from PGE Editor in the SMBX 2.0 repo. No problem at all, provided you only install lunadll.dll and lunadll.pdb

What is occurring for you, is probably a DLL dependency problem. I can duplicate the problem you have, if I try to use the latest SDL2_mixer_ext.dll you've added to be distributed with LunaLua. It requires other DLLs, which are not present and/or the wrong version.

I looked into this more a couple weeks ago. If I remember correctly, the existing libgcc_s_dw2-1.dll  in the smbx 2.0 repo was of a version that was incompatible with this new build of SDL2_mixer_ext.dll.... but you can't simply change that because the version that works for this new SDL2_mixer_ext.dll is incompatible with SMBXLauncher.exe

**Comment by Wohlstand** [comment]
I think, that because new SDL Mixer X used MinGW 5.3 instead of 4.9, therefore another dependency. I'll try to rebuild SDL, all dependent libraries and Mixer with a new MinGW version

**Comment by Wohlstand** [comment]
Okay, placing of RIGHT  libgcc_s_dw2-1.dll and ligstdc++-6.dll fixes this trouble. I just successfully ran a test from PGE Editor. However still a racing causes freezing on slow machines when game is almost started. That another issue.
